AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Scheduled Lambda Creation
Resources:
  ManagerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join 
                  - ''
                  - - !Ref 'AWS::StackName'
                    - '-'
                    - 'manager'
      CodeUri: 's3://my-lambda-blog-test/Lambda.zip'
      Handler: index.handler
      Runtime: nodejs8.10
      Description: My Lambda
      MemorySize: 128
      Timeout: 15
  ManagerLambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join
          - ''
          - - !Ref 'AWS::StackName'
            - '-'
            - 'manager-rule' 
      Description: 'Triggers manager lambda once per day'
      ScheduleExpression: 'cron(0 7 ? * * *)'
      Targets:
        -
          Arn: !GetAtt ManagerLambda.Arn
          Id: TargetFunctionV1
  ManagerLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ManagerLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ManagerLambdaScheduledRule.Arn     

